# Generated by Django 4.1.7 on 2023-04-03 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='departments',
            name='s_no',
            field=models.IntegerField(default=1),
        ),
    ]
